### ISSUE TITLE
error: user name does not exist

### ISSUE THREAD

**Issue by InitialBug** [ManhTruongDang/check-gpu#1]
When I run the command,it raises the error. Following is the details:

`error: user name does not exist

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
`

How to solve this problem?

**Comment by dangmanhtruong1995** [comment]
Well, I wouldn't call it a bug but instead an unwanted feature. This happens when no user is currently running the GPU. Since I'm not that good with Bash, I'm afraid it would take a while for me to fix it.
To be honest I think it is best to live with it :)

**Comment by InitialBug** [comment]
@ManhTruongDang But actually the GPU is running when I use this bash code

**Comment by dangmanhtruong1995** [comment]
Have you checked with nvidia-smi ? What is the output?

2018-07-09 10:01 GMT+07:00, InitialBug <notifications@github.com>:

**Comment by Ir1d** [comment]
@InitialBug that's because `tail -n 16` didn't remove all useless lines. You need to change 16 into your own case, which is the number of lines before the PIDs. 16 is for  one GPU i guess.
